### ISSUE TITLE
Dashboard output broken

### ISSUE THREAD

**Issue by ottok** [Seravo/wp-dashboard-log-monitor#5]
This plugin has been broken for months now. Opening this issue as a reminder. Today latest version 1.0.3 still outputs in the dashboard the stuff visible on the screenshot below:
![kuvakaappaus 2015-05-15 12 54 01](https://cloud.githubusercontent.com/assets/668724/7650721/fb706ae6-fb01-11e4-8df7-f65f81889354.png)

**Comment by onnimonni** [comment]
fixed in f05a662570ef414940341bd313508fc2d9834494
